### ISSUE TITLE
Process feedback Florian Hartig

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/thesis#11]
From @florianhartig:

As said in my motivation, I enjoyed reading this text. The introduction and the question for the thesis was presented unusually crisp. In particular the overall research questions of the thesis is crystal clear. As a minor (optional) comment, I would suggest that the summary of the main chapters at the end of the introduction could be slightly expanded, either in the text, or possibly in a table / figure. A table would also provide the opportunity to clarify the publication status and availability of the manuscripts. I see that the first paper has been published in MEE, and at least one other is on bioArxiv?    My main comment regarding the scientific results of this work is that, especially given the substantial investment of time for building this pipeline, it is somewhat unfortunate that there was no time left to examine the influence of the tree prior in more detail. I was not fully convinced (and I think neither are you) that a wrong tree prior is always so inconsequential as it turned out to be in the case of the multiple birth death (MBD) model. My suspicion is that this model, while possibly of theoretical interest, is as a generative model nearly undistinguishable from a standard BD model, as that therefore differences in tree topology only occur locally (e.g.  a double branching event, where in the standard BD model, you would have two single branching events, but if you zoom out, it’s more or less the same). I would suspect that generative models that lead to topologically more distinct trees also lead to stronger differences in the inference of the tree. I realize, however, that you are probably aware of all this (it is also discussed in the text), and that only the issue of time prevented you to further explore these points. I therefore do not see a need to do any changes to the text regarding these points, unless you want to make some clarifications in the light of these remarks.    The final discussion section was somewhat unusual to read, as it provides a really wide sweep of topics and arguments beyond the immediate scientific questions of the thesis. I refer to topics such as “what is the purpose of science”, the OS framework, but also the various attempts to quantify the value of scientific software. I have no formal objection to this part; in fact, I found it rather refreshing. Nevertheless, I would note that it did appear to me a bit defensive at times, in particular where comments relate to the value of this work, and how to measure it. Again, there is no need to make changes here from my side. None of what is said here is factually wrong, and I feel you should have the right to summarize your PhD in the way you want. Still, if you want to make changes to this part, my recommendation would be to direct the attention more forward, to the question of if and how we can infer accurate phylogenetic trees from molecular data, rather than spending time in the past and in side discussions. But again, this is a fully optional comment, no requirement to make changes.     

As a last comment, although it is clearly too early to congratulate, I wanted to close by saying that I truly appreciate the work that has been done here. I think it’s important to get a better appreciation of the robustness of these tools that are fundamental to the entire field, and I feel that this work makes a small, but nevertheless important step in this direction.

As said in my motivation, I enjoyed reading this text. The introduction and the question for the thesis was presented unusually crisp. In particular the overall research questions of the thesis is crystal clear. As a minor (optional) comment, I would suggest that the summary of the main chapters at the end of the introduction could be slightly expanded, either in the text, or possibly in a table / figure. A table would also provide the opportunity to clarify the publication status and availability of the manuscripts. I see that the first paper has been published in MEE, and at least one other is on bioArxiv?    My main comment regarding the scientific results of this work is that, especially given the substantial investment of time for building this pipeline, it is somewhat unfortunate that there was no time left to examine the influence of the tree prior in more detail. I was not fully convinced (and I think neither are you) that a wrong tree prior is always so inconsequential as it turned out to be in the case of the multiple birth death (MBD) model. My suspicion is that this model, while possibly of theoretical interest, is as a generative model nearly undistinguishable from a standard BD model, as that therefore differences in tree topology only occur locally (e.g.  a double branching event, where in the standard BD model, you would have two single branching events, but if you zoom out, it’s more or less the same). I would suspect that generative models that lead to topologically more distinct trees also lead to stronger differences in the inference of the tree. I realize, however, that you are probably aware of all this (it is also discussed in the text), and that only the issue of time prevented you to further explore these points. I therefore do not see a need to do any changes to the text regarding these points, unless you want to make some clarifications in the light of these remarks.    The final discussion section was somewhat unusual to read, as it provides a really wide sweep of topics and arguments beyond the immediate scientific questions of the thesis. I refer to topics such as “what is the purpose of science”, the OS framework, but also the various attempts to quantify the value of scientific software. I have no formal objection to this part; in fact, I found it rather refreshing. Nevertheless, I would note that it did appear to me a bit defensive at times, in particular where comments relate to the value of this work, and how to measure it. Again, there is no need to make changes here from my side. None of what is said here is factually wrong, and I feel you should have the right to summarize your PhD in the way you want. Still, if you want to make changes to this part, my recommendation would be to direct the attention more forward, to the question of if and how we can infer accurate phylogenetic trees from molecular data, rather than spending time in the past and in side discussions. But again, this is a fully optional comment, no requirement to make changes.     

As a last comment, although it is clearly too early to congratulate, I wanted to close by saying that I truly appreciate the work that has been done here. I think it’s important to get a better appreciation of the robustness of these tools that are fundamental to the entire field, and I feel that this work makes a small, but nevertheless important step in this direction.

Thanks @florianhartig!

**Comment by Giappo** [comment]
As MBD was mentioned I feel that I can say add something more to the discussion.
A possibility is that pirouette was unable to find differences between the generative MBD tree as compared with the posterior BD trees because the statistics used to compute the errors was not adequate.
With my coauthors we are currently employing a different statistics (Distance from Nearest Branching Time, or DNBT) that instead seems to highlight the fundamental differences between the two model. What our data results seems to suggest is that the signal that best explain this difference is the clustering of the branching times, properly captured by DNBT.
For additional information you can contact me in private form, as this data is likely to be used in a future publication.

**Comment by richelbilderbeek** [comment]
Added to README :+1:
